### ISSUE TITLE
Trying to import.

### ISSUE THREAD

**Issue by danielrosero** [benletchford/python-firebase-gae#2]
Hey, im new on GAE, and I'm trying to use your library so I can modify some information I got on a Firebase Database.

Im trying to import your library, but I'm having a hard time.
Is this the right way? 
https://cloud.google.com/appengine/docs/python/tools/using-libraries-python-27#installing_a_third-party_library

Thanks

**Comment by benletchford** [comment]
Hi Daniel,

There's nothing special about using third-party libs on GAE - those instructions are fine.

Here's some additional detailed instructions on using this library: http://stackoverflow.com/a/38304570
